### ISSUE TITLE
No module named 'multiprocess'

### ISSUE THREAD

**Issue by rxu2** [bcdaniels/coniii#18]
Can not import the master branch. Installed with python3. Is this still actively developed?

```python3
Traceback (most recent call last):
  File "setup.py", line 29, in <module>
    from coniii.version import version as __version__
  File "<...>/coniii/__init__.py", line 23, in <module>
    from .solvers import MCH,MPF,Pseudo,ClusterExpansion,Enumerate,RegularizedMeanField
  File "<...>/coniii/solvers.py", line 28, in <module>
    import multiprocess as mp
ModuleNotFoundError: No module named 'multiprocess'
```

**Comment by bcdaniels** [comment]
Hi, 
We’ve moved to https://github.com/eltrompetero/coniii .  Try the code there and let us know if you still run into this issue?  Thanks

**Comment by rxu2** [comment]
yup. still has issue.
